/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaForm;

import java.awt.BorderLayout;
import java.awt.Component;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author sieus
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmStudent = new javax.swing.JFrame();
        frmDesktop = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuItemOpen = new javax.swing.JMenuItem();
        menuItemSaveFile = new javax.swing.JMenuItem();
        menuItemPassword = new javax.swing.JMenuItem();
        menuStudent = new javax.swing.JMenu();
        menuItemListAll = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuScore = new javax.swing.JMenu();
        menuItemScore = new javax.swing.JMenuItem();
        menuTimetable = new javax.swing.JMenu();
        menuItemTimetable = new javax.swing.JMenuItem();

        javax.swing.GroupLayout frmStudentLayout = new javax.swing.GroupLayout(frmStudent.getContentPane());
        frmStudent.getContentPane().setLayout(frmStudentLayout);
        frmStudentLayout.setHorizontalGroup(
            frmStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frmStudentLayout.setVerticalGroup(
            frmStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmMainForm"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout frmDesktopLayout = new javax.swing.GroupLayout(frmDesktop);
        frmDesktop.setLayout(frmDesktopLayout);
        frmDesktopLayout.setHorizontalGroup(
            frmDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        frmDesktopLayout.setVerticalGroup(
            frmDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        menuHome.setText("File");
        menuHome.setActionCommand("Home");

        menuItemOpen.setText("Open file");
        menuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenActionPerformed(evt);
            }
        });
        menuHome.add(menuItemOpen);

        menuItemSaveFile.setText("Save file");
        menuHome.add(menuItemSaveFile);

        menuItemPassword.setText("Change Password");
        menuItemPassword.setToolTipText("");
        menuHome.add(menuItemPassword);

        jMenuBar.add(menuHome);

        menuStudent.setText("Student");
        menuStudent.setToolTipText("");

        menuItemListAll.setText("Student");
        menuItemListAll.setActionCommand("Load ");
        menuItemListAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListAllActionPerformed(evt);
            }
        });
        menuStudent.add(menuItemListAll);

        jMenuItem1.setText("jMenuItem1");
        menuStudent.add(jMenuItem1);

        jMenuBar.add(menuStudent);

        menuScore.setText("Score");

        menuItemScore.setText("Score");
        menuItemScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemScoreActionPerformed(evt);
            }
        });
        menuScore.add(menuItemScore);

        jMenuBar.add(menuScore);

        menuTimetable.setText("Timetable");

        menuItemTimetable.setText("Timetable");
        menuItemTimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTimetableActionPerformed(evt);
            }
        });
        menuTimetable.add(menuItemTimetable);

        jMenuBar.add(menuTimetable);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frmDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frmDesktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void menuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        // int returnValue = jfc.showSaveDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jfc.getSelectedFile();
                System.out.println(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_menuItemOpenActionPerformed
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:        
        
    }//GEN-LAST:event_formWindowOpened

    private void menuItemListAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListAllActionPerformed
        // TODO add your handling code here:
        frmDesktop.removeAll();
        FormStudent frm = new FormStudent();
        int frmWidth = this.getWidth();
        int frmHeight = this.getHeight();
        frm.setSize(frmWidth, frmHeight);
        frmDesktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_menuItemListAllActionPerformed

    private void menuItemScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemScoreActionPerformed
        // TODO add your handling code here:
        frmDesktop.removeAll();
        FormScore frm = new FormScore();
        int frmWidth = this.getWidth();
        int frmHeight = this.getHeight();
        frm.setSize(frmWidth, frmHeight);
        frmDesktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_menuItemScoreActionPerformed

    private void menuItemTimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTimetableActionPerformed
        // TODO add your handling code here:
        frmDesktop.removeAll();
        FormTimetable frm = new FormTimetable();
        int frmWidth = this.getWidth();
        int frmHeight = this.getHeight();
        frm.setSize(frmWidth, frmHeight);
        frmDesktop.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_menuItemTimetableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane frmDesktop;
    private javax.swing.JFrame frmStudent;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenuItem menuItemListAll;
    private javax.swing.JMenuItem menuItemOpen;
    private javax.swing.JMenuItem menuItemPassword;
    private javax.swing.JMenuItem menuItemSaveFile;
    private javax.swing.JMenuItem menuItemScore;
    private javax.swing.JMenuItem menuItemTimetable;
    private javax.swing.JMenu menuScore;
    private javax.swing.JMenu menuStudent;
    private javax.swing.JMenu menuTimetable;
    // End of variables declaration//GEN-END:variables
}
